### ISSUE TITLE
sh: 0: Can't open ./deploy.sh

### ISSUE THREAD

**Issue by MarkHardwick-Dev** [blombard/lambda-monorepo#14]
Hi, thanks very much for making this GitHub action! 

However when trying to use this I get the following:

### 🐛 Error 
```
Run blombard/lambda-monorepo@v0.6.1
  with:
    lambda-functions: {
    "health": "true",
    "addChargerSite": "true"
  }
    zip-params: *.js *.json src/ node_modules/
    alias-name: production
  env:
    AWS_DEFAULT_REGION: ***
    AWS_REGION: ***
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
sh: 0: Can't open ./deploy.sh
Deployment of health failed!
sh: 0: Can't open ./deploy.sh
Deployment of addChargerSite failed!
Error: An error occured. At least one Lambda could not be deployed.
```

Are the file permissions correctly set on deploy.sh?

**Comment by MarkHardwick-Dev** [comment]
Solved by copying deploy.sh into my repo root

**Comment by blombard** [comment]
Sorry for not answering @MarkHardwick-Dev, I don't have time to check now but you can indeed override the default `deploy.sh` with one in your repo. Glad it solved your problem. I'll check when times permit 🙂
